services:
  - type: web
    name: shanti-express
    env: python
    buildCommand: ""
    startCommand: python app.py
    disk:
      name: uploads-disk
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
    envVars:
      - key: PORT
        value: 10000
